# -*- coding: utf-8 -*-
"""Veronika Bystrykh

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xf72qcqZKwMxZcM34K_RkALrqrV09Jd0
"""

import requests
response = requests.get ('https://example.com')
response.ok

response.text

from bs4 import BeautifulSoup
html = BeautifulSoup(response.text)
html

response = requests.get('https://34travel.me/tags/belarus')
response.ok

html = BeautifulSoup(response.text)
html

one_link = html.find('a', {'class': 'b-main__list__link' })
one_link

links = html.select('a.b-main__list__link')
links

for link in links:
  print(link['href'], link.text)

Here i have some problems with the None parameter and could'nt fix them by ".dropna" or "if X is not None" way

posts = html.select('div')
for post in posts:
  link = post.select_one('a.b-main__list__link')
  print(link)

result_list = []
for post in posts:
  next = post.find_next_sibling('div.b-main')
  title = post.select_one('h2.b-news__short__title')
  text = post.select_one('div.b-news__short__text')
  score = post.select_one('span.b-news__short__view')
  category = post.select_one('span.b-news__short__category')
  result_list.append({
    'title': title,
    'text': text,
    'category': category,
    'score': score,
  })
result_list

import pandas as pd
table = pd.DataFrame(result_list).convert_dtypes()
table